### ISSUE TITLE
Edit on codepen button not working correctly

### ISSUE THREAD

**Issue by rubenmoya** [CartoDB/shuttle#4]
### Description
The `Edit on codepen` button only works if you don't click on the text

### Image
![codepen](https://user-images.githubusercontent.com/905225/46220007-2f655880-c349-11e8-9a4a-cec1800672df.gif)

**Comment by rjimenezda** [comment]
It also happens for the Zip file, it's because of the wacky layout that we're doing with the iframe and the mock browser.
